### ISSUE TITLE
Top level @include not working with compressed output style

### ISSUE THREAD

**Issue by gradyetc** [sindresorhus/grunt-sass#142]
I'm seeing a regression in top-level @include behavior since 0.16.0.

Given the following:

``` scss

@mixin breakpoint() {
    @media (min-width: 500px) {
        @content;
    }
}

@include breakpoint {
    .foo {
        color: blue;
    }
}
```

The expected output with 'compressed' style is:

``` css
@media (min-width: 500px){.foo{color:blue;}}
```

But with 0.16.0 I'm getting this:

``` css
@media (min-width: 500px){}
```

It works fine if I use the 'expanded' output style:

``` css
@media (min-width: 500px) {
  .foo {
    color: blue; }
 }
```
