### ISSUE TITLE
Possibility to remove the comments in CSS

### ISSUE THREAD

**Issue by visualcookie** [sindresorhus/grunt-sass#160]
Hi,

didn't found that in the Issue board nor the Documentation. Is there an option where I can remove the line comments in the compiled CSS?

Output currently is a bit odd if there are these developer comments:

``` css
/* line 1, C:/Users/Dean/Desktop/libsass_base/_sass/site.scss */
header {
  background: #000;
  color: #fff; }
  /* line 5, C:/Users/Dean/Desktop/libsass_base/_sass/site.scss */
  header h1 {
    font-size: 80px; }
  /* line 9, C:/Users/Dean/Desktop/libsass_base/_sass/site.scss */
  header.container {
    width: 1200px; }

/*# sourceMappingURL=site.css.map */
```
