### ISSUE TITLE
Double \ instead of single

### ISSUE THREAD

**Issue by kelnar** [sindresorhus/grunt-sass#250]
This snippet is coming from Bootstrap from _breadcrumb.scss

```scss
$breadcrumb-separator: "/" !default;
.breadcrumb {
  > li {
    + li:before {
      content: "#{$breadcrumb-separator}\00a0"; // Unicode space added since inline-block means non-collapsing white-space
	}
  }
}
  
```

is compiled to: 
```scss
.breadcrumb > li + li:before {
  content: "/\\00a0"; 
}
```

There is double ```\\``` and should be single ```\```
