### ISSUE TITLE
Comments in rules

### ISSUE THREAD

**Issue by LeusMaximus** [sindresorhus/grunt-sass#259]
Hi. Is it possible to make that comments into rules don't removed after compiling?
```css
.block {
  font-size: 20px /*rtl:18px*/;
}
```
