### ISSUE TITLE
Placeholders compiling improperly

### ISSUE THREAD

**Issue by davidtheclark** [sindresorhus/grunt-sass#39]
I'm not sure whether this is a problem with grunt-sass or with node-sass ... but here's what's happening:

If I use grun-sass to compile this file ---- https://github.com/davidtheclark/scss-utils/blob/master/src/components/_lists.scss, which contains nothing but mixins and placeholders ---- I get the following outputted CSS:

``` css
%u-list-float, %u-list-inline, %u-list-comma {
  list-style-type: none;
  margin: 0;
  padding: 0; }

%u-list-float > li {
  float: left; }
```

That's suggesting that the compiler isn't properly handling @extend placeholders.

If I compile the same file with grunt-contrib-sass, I get no such weirdness ---- it works fine.
