### ISSUE TITLE
Broken Selectors with silent classes

### ISSUE THREAD

**Issue by jpdevries** [sindresorhus/grunt-sass#40]
When extending silent classes from within another silent class, grunt-sass is producing bad selectors. grunt-contrib-sass generates correct selectors.

gist package that reproduces the issue here:
https://gist.github.com/jpdevries/6350682

this:

``` scss
%visuallyhidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}

%focusable:active,
%focusable:focus {
    clip: auto;
    height: auto;
    margin: 0;
    overflow: visible;
    position: static;
    width: auto;
    @extend %visuallyhidden;
}

#mydiv {
    @extend %visuallyhidden;
}
```

generates:

``` scss
%focusable:active, %focusable:focus, #mydiv { /* bad selector generated by grunt-sass (grunt-contrib-sass works correclty) */
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px; }



```
