### ISSUE TITLE
sass-boostrap compilation fails

### ISSUE THREAD

**Issue by ain** [sindresorhus/grunt-sass#47]
Something that succeeds in `grunt-contrib-compass`, fails in `grunt-sass`:

> Warning: app/bower_components/sass-bootstrap/lib/mixins:712: error: invalid selector after ,

ln 708-712 in mixins:

``` scss
@mixin make-lg-column-pull($columns) {
  @media (min-width: $screen-lg-min) {
    right: percentage(($columns / $grid-columns));
  }
}
```
