### ISSUE TITLE
Tabbing present on compiled css

### ISSUE THREAD

**Issue by Gioyik** [sindresorhus/grunt-sass#66]
SASS source:

``` scss
.item-edit {
  @include transition(left 0.2s ease-in-out, opacity 0.2s ease-in-out);
  position: absolute;
  top: 0;
  left: 8px;
  z-index: $z-index-item-edit;
  width: 48px;
  height: 100%;
  line-height: 100%;

  .button {
    height: 100%;

    &.icon {
      @include display-flex();
      @include align-items(center);
      position: absolute;
      top: 0;
      left: 0;
      height: 100%;
      color: $assertive;
      font-size: 24px;
    }
  }

  &.ng-enter {
    @include transition(left 0.2s ease-in-out, opacity 0.2s ease-in-out);
    left: -48px;
    opacity: 0;
  }
  &.ng-enter-active {
    left: 8px;
    opacity: 1;
  }
  &.ng-leave {
    @include transition(left 0.2s ease-in-out, opacity 0.2s ease-in-out);
    left: 0px;
    opacity: 1;
  }
  &.ng-leave-active {
    left: -48px;
    opacity: 0;
  }
}
```

Compiled CSS:

``` css
.item-edit {
  -webkit-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  -moz-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  position: absolute;
  top: 0;
  left: 8px;
  z-index: 0;
  width: 48px;
  height: 100%;
  line-height: 100%; }
  .item-edit .button {
    height: 100%; }
    .item-edit .button.icon {
      display: -webkit-box;
      display: -webkit-flex;
      display: -moz-box;
      display: -moz-flex;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      -moz-align-items: center;
      align-items: center;
      position: absolute;
      top: 0;
      left: 0;
      height: 100%;
      color: #ef4e3a;
      font-size: 24px; }
  .item-edit.ng-enter {
    -webkit-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
    -moz-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
    transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
    left: -48px;
    opacity: 0; }
  .item-edit.ng-enter-active {
    left: 8px;
    opacity: 1; }
  .item-edit.ng-leave {
    -webkit-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
    -moz-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
    transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
    left: 0px;
    opacity: 1; }
  .item-edit.ng-leave-active {
    left: -48px;
    opacity: 0; }
```

Correct space for tabbing on compiled CSS:

``` css
.item-edit {
  -webkit-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  -moz-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  position: absolute;
  top: 0;
  left: 8px;
  z-index: 0;
  width: 48px;
  height: 100%;
  line-height: 100%;
}
.item-edit .button {
  height: 100%;
}
.item-edit .button.icon {
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -moz-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-align: center;
  -ms-flex-align: center;
  -webkit-align-items: center;
  -moz-align-items: center;
  align-items: center;
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  color: #ef4e3a;
  font-size: 24px;
}
.item-edit.ng-enter {
  -webkit-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  -moz-transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  transition: left 0.2s ease-in-out, opacity 0.2s ease-in-out;
  left: -48px;
  opacity: 0;
}
.item-edit.ng-enter-active {
  left: 8px;
  opacity: 1;
}
```
